name: Release

on:
  push:
    tags:
      - 'v*' 

permissions:
  contents: write  

jobs:
  publish:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'sbt'

      - name: Build JAR
        run: sbt package

      - name: Create GitHub Release and Upload JAR
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          files: target/scala-*/**/*.jar
